### ISSUE TITLE
spacemacs relies on evil-escape to be in melpa. It is not in Melpa and spacemacs doesn't work.

### ISSUE THREAD

**Issue by truthseekers** [melpa/melpa#8227] opened 2022-10-10 19:19 UTC
Description :octocat:
<>
Spacemacs fails to install the package "evil-escape" and provides the following message:

"Package evil-escape is unavailable. Is the package name misspelled?"

the evil-escape githup repo claims its available in Melpa:

https://github.com/syl20bnr/evil-escape

However, it doesn't appear to be. https://melpa.org/ shows no "evil-escape" when searching with their filter.

Reproduction guide 🪲
Start Emacs
<>
delete / rename .emacs/d folder
git clone https://github.com/syl20bnr/spacemacs $HOME/.emacs.d
open emacs so it installs all spacemacs defaults. (should fail to install evil-escape)
Not sure if reproduction steps will work if you already have evil-escape from an older version of melpa, but mine fails due to not having evil-escape in melpa.

Observed behaviour: 👀 💔
<>

Cannot run SPC f or a variety of sapcemacs commands.

Expected behaviour: ❤️ 😄
<>

Should be able to run SPC f and other spacemacs commands.

System Info 💻
OS: windows-nt
Emacs: 28.2
Spacemacs: 0.999.0
Spacemacs branch: develop (rev. https://github.com/syl20bnr/spacemacs/commit/264a8ffc203a3215623330576941d1722bbee1e4)
Graphic display: t
Running in daemon: nil
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers:
(helm emacs-lisp)
System configuration features: ACL GIF GMP GNUTLS HARFBUZZ JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY W32NOTIFY PDUMPER PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XPM ZLIB
Backtrace 🐾
<<BACKTRACE IF RELEVANT>>

**Comment by purcell** [comment] 2022-10-10 20:16
Paging @tarsius — it looks like a decision was made to drop this package in ff1dc27f010a6a097755bccd5e29985602cd0194, which references https://github.com/syl20bnr/evil-escape/pull/98. While perhaps abrupt, and perhaps even a little more zealous than I might have been personally, this is a basic package formatting issue which has gone unfixed since 2018, when a still-unmerged fix for the same problem was first offered: https://github.com/syl20bnr/evil-escape/pull/86

It looks like @syl20bnr nominated other maintainers for Spacemacs, and I'd suggest he should do the same thing for this other package so that trivial fixes can get merged.

**Comment by lebensterben** [comment] 2022-10-10 20:42
I may fork it when I got time...

**Comment by minad** [comment] 2022-10-10 21:03
FWIW I think https://github.com/melpa/melpa/commit/ff1dc27f010a6a097755bccd5e29985602cd0194 should be reverted. I don't use evil-escape, but it doesn't seem okay to drop packages from MELPA only because they haven't been updated for a while. This seems like an arbitrary decision.

The fix was offered only in 2018 which isn't long ago at all. There are many useful packages on MELPA which haven't seen updates for a longer time, e.g., macrostep with last update in 2016 and multiple open issues. Could dropping be clarified in the policy please? Dropping should be handled carefully and conservatively. In my opinion, legitimate reasons seem to be:

- Package is malicious (or turned malicious) -> Immediate drop
- Package doesn't compile anymore with recent Emacs. Currently I think a package should at least compile on Emacs 27 OR Emacs 28. It should be okay if a package doesn't compile with the newest stable release given that upstream is changing things in a quicker pace these days. -> Drop after a warning mail to the maintainer after a month or two?
- Package has a serious bug which didn't get fixed for a long time. The bug should affect the setup as a whole. A serious bug in the package functionality itself shouldn't be a reason for dropping as long as the package is still somewhat functional. -> Drop after a warning mail to the maintainer.
- More reasons?

**Comment by tarsius** [comment] 2022-10-10 21:10
Sight.

Yes, I had a "fuck this, if I don't break it, this will never get fixed" moment. I didn't even read what you wrote, I am sure it's all the truth. I'll immediately fork to the orphanage, apply the fix, and update Melpa to get it from there. Yeah! Another package I get to (semi-)maintain. How wonderful.

**Comment by minad** [comment] 2022-10-10 21:16
@tarsius I don't understand why these minor typos even justify forking the package to the orphanage. I think the packages should just be left alone as they are. Maybe lm-summary should be fixed instead to handle these issues more gracefully, or maybe not? Anyway, lm-summary is not crucial functionality which can be considered in the same ballpark as "not building on recent Emacs". From my experience the functionality exposed by lisp-mnt is rather weak and could be thrown away even. For example I couldn't make use of the functionality in my Marginalia package due to performance reasons and robustness issues.

**Comment by tarsius** [comment] 2022-10-10 21:29
I am not gonna read that because I expect I would feel worse afterwards.

Anyway, the package has been restored, though it might take until the rebuild cycle until it becomes available again.

**Comment by minad** [comment] 2022-10-10 21:39
Hmm, @tarsius I didn't write my comment with bad intentions in mind or with the intention of attacking you. I also understand your sentiment of just throwing something out if it doesn't play by the rules.

**Comment by tarsius** [comment] 2022-10-10 21:41
> Hmm, @tarsius I didn't write my comment with bad intentions in mind or with the intention of attacking you. I also understand your sentiment of just throwing something out if it doesn't play by the rules.

Thanks for your understanding.

> :-1: 

I am a bit of a emotional crisis here. @sfalmo thanks for the compassion and downvote.

**Comment by sfalmo** [comment] 2022-10-10 22:08
I also don't want to attack you, @tarsius, but breaking emacs completely because of a somewhat minor issue in a package seems a bit drastic to me. It is very unfortunate, but my distro had a major update today which included emacs 28.2. Therefore, emacs/spacemacs packages were updated as well, making emacs unusable due to the temporary removal of evil-escape. Certainly, there are a lot of people who had/have this issue that are now driven away from emacs, so I think this should have been handled more carefully.

**Comment by progfolio** [comment] 2022-10-10 22:26
> breaking emacs completely because of a somewhat minor issue in a package 

Emacs isn't broken. Spacemacs was. Big difference.

> Certainly, there are a lot of people who had/have this issue that are now driven away from emacs, so I think this should have been handled more carefully.

Spare the histrionics. This isn't a big deal.

I  agree with tarsius's decision to drop those packages . It's up to the people who are interested in that package to maintain it. Package health isn't the responsibility of a curator. The decision to drop or include packages which do not adhere to a standard are.

**Comment by tarsius** [comment] 2022-10-10 23:04
It's back at https://melpa.org/#/evil-escape and I added a note to the repository formerly known as upstream.

**Closed by tarsius** 2022-10-10 23:04 UTC

**Comment by purcell** [comment] 2022-10-11 08:47
From @minad 
> Anyway, lm-summary is not crucial functionality. It cannot be considered in the same ballpark as "not building on recent Emacs". From my experience the functionality exposed by lisp-mnt is rather weak and could be thrown away even. For example I couldn't make use of the functionality in my Marginalia package due to performance reasons and robustness issues.

I think there's a misunderstanding here: `lm-summary` is not the whole story. With that extra space, the `package-buffer-info` function fails completely, so _none_ of the declared package dependencies or metadata can be extracted from the code. I don't think we could argue that MELPA should try to fix that up automatically or work around it, and it's very suboptimal to have malformed packages in MELPA.

Yes, this was an abrupt change, and I might have suggested we publicly declare a deadline by which the package would be removed if unfixed, but I generally support @tarsius in having triggered some disruption, so that we can have a useful conversation like this. Hopefully it is more evident now that Spacemacs is build on some unmaintained code that fails to meet some basic requirements.

It's worth noting that Jonas has done some extra work here for the community by making a fork and applying this fix. An ideal outcome now would be that someone who cares about this package would take over maintainership of the original package (ideally at its original location, or via a repo transfer from that place to a new home), then we would be delighted to change the recipe to build from there instead.

**Comment by minad** [comment] 2022-10-11 10:02
@purcell I agree that broken/malformed packages should be kicked out. I wasn't aware of the extent of the breakage caused by this. I agree with you that some grace period would have been nice and that it would be good to make it clear that the package is about to be dropped from MELPA if a PR is not merged.

**Comment by smile13241324** [comment] 2022-10-19 20:38
Thanks for the help @tarsius and @purcell. You are right maintaining these old packages is definitely not your job I will do a fork and try to take over maintenance. Thanks for the extra work you have put into this and your patience!

**Comment by real-or-random** [comment] 2023-11-19 11:49
@smile13241324 @tarsius 


> Thanks for the help @tarsius and @purcell. You are right maintaining these old packages is definitely not your job I will do a fork and try to take over maintenance. 

The forking was done, but maintenance wasn't "officially" changed. The current situation appears to be that [@smile13241324's fork](https://github.com/smile13241324/evil-escape/tree/master) is maintained. So that means that MELPA could point to that package instead of [@tarsius's fork in the orphanage](https://github.com/emacsorphanage/evil-escape/tree/master). I don't really know how MELPA works, but I assume one could just open a PR that changes the URL if @tarsius agrees. @smile13241324 Would you be willing to care of this?

Note that the two forks have strictly speaking diverged, but [the changes in the orphanage](https://github.com/syl20bnr/evil-escape/compare/master...emacsorphanage:evil-escape:master) are entirely trivial.

**Comment by smile13241324** [comment] 2023-11-19 13:01
Sorry guys I was off for some weeks due to some crazy release schedules in one of my paid projects.

Yes I would be willing to take over maintenance but I have not yet found the time to make the package adhere to the proper melpa standards.

@tarsius is it ok to take the package over as it is or do you want me to reform it first?

**Comment by tarsius** [comment] 2023-11-22 23:02
I caused some disruption when removing this package, and it's important to me to avoid doing that again.

The way of least resistance would be for me to just bless @smile13241324 as the new maintainer. Unfortunately after reviewing the changes in her fork, I am not comfortable doing that. When we handover an existing package to a new maintainer, we do have to decide whether they have the necessary experience and in this case I have come to the conclusion that this is not the case. 

Please try not to be offended that I have come to that conclusion.

Instead I have spend some time today, integrating some of the same changes you have integrated in your fork. And I have informed the authors of outstanding pull-requests that they might want to consider re-opening them in the new repository. (This is one area where I disagreee with what you have done. It seems to me that you just merged all open prs, instead of carefully evaluating each one on its own merit.)

**Comment by real-or-random** [comment] 2023-11-23 10:28
> The way of least resistance would be for me to just bless @smile13241324 as the new maintainer. Unfortunately after reviewing the changes in her fork, I am not comfortable doing that. When we handover an existing package to a new maintainer, we do have to decide whether they have the necessary experience and in this case I have come to the conclusion that this is not the case.
> 

I think it would be fair to let her know what considerations went into this decision. You mentioned just one consideration.

My impression is that the decision is bit hasty. The wiki says: "The new maintainer must have experience. E.g. maintains/contributes to an existing elisp package, has other visible community contributions, or can be vouched for by such a person."

@smile13241324 is a maintainer of spacemacs and has a [some significant number of commits](https://github.com/syl20bnr/spacemacs/commits?author=smile13241324) there. (spacemacs is strictly speaking not an elisp package, but I'm sure these are other community contributions).    

> (This is one area where I disagreee with what you have done. It seems to me that you just merged all open prs, instead of carefully evaluating each one on its own merit.)

First, you don't really know what amount of evaluation went into the decision to merge PR. Moreover, the primary purpose of her fork was to keep the package working in spacemacs. Whether a package works just in spacemacs is easier to evaluate by just testing it there. Sure, quality matters. But what I'm trying to say is that the evaluation criteria for this fork were different from the maintenance rules in MELPA. And she is fully aware of that! (She said "Yes I would be willing to take over maintenance but I have not yet found the time to make the package adhere to the proper melpa standards.") 

So if you ask me (but you don't have to), a more appropriate response would have been to indicate the required changes and standards and ask her to make these changes and adhere to these standards.

Ignoring all of this, I (and I believe other users) can live with the current situation that you take care of the package, and if this is the way to go, I'm happy.

**Comment by smile13241324** [comment] 2023-11-25 03:31
Don't worry @tarsius I am not offended, I am just happy that this package got a new maintainer after all, this really doesn't need to be me.

Still I would like to take some time to carefully test if we have not lost functionality by jumping back to the original package state.

I remember I have introduced some escape features, which were originally offered to Spacemacs, and I don't want to risk regression by blindly switching back.

@real-or-random Thanks for your kind words! 💜
