### ISSUE TITLE
Download stats dead since 2016-09-06

### ISSUE THREAD

**Issue by cpitclaudel** [melpa/melpa#4232] opened 2016-09-10 19:08 UTC
Looks like download stats have not been updated since 2016-09-06 (download counts have not changed for any packages in the last 4 days). 

Can I help?

**Comment by purcell** [comment] 2016-09-10 23:38
Duplicate of #4231.

**Closed by purcell** 2016-09-10 23:38 UTC

**Comment by cpitclaudel** [comment] 2016-09-11 00:07
Looks like we posted these at roughly the same time :) Sorry for the noise!

**Comment by purcell** [comment] 2016-09-11 01:12
All good. :-)
