### ISSUE TITLE
Indented sub-lists in package description text

### ISSUE THREAD

**Issue by Boruch-Baum** [melpa/melpa#7398] opened 2021-01-29 15:40 UTC
refs:
 [1] https://melpa.org/#/diredc
 [2] https://github.com/Boruch-Baum/emacs-diredc/blob/main/diredc.el
 [3] https://github.com/Boruch-Baum/emacs-diredc

The MELPA summary page[1] seems to be parsing the package's description from the elisp commentary[2], but doesn't account for the indented sub-lists there. Compare with the markdown output[3].

The result will be confusing to readers. It's confusing to me, and I'm the author!

I'd be willing to alter the elisp commentary to get the desired result, if you can tell me how to re-format it, or you can handle it on your side.

**Comment by tarsius** [comment] 2021-02-04 22:19
This appears to be a regression in `lm-commentary`. It would be best to fix it there. If you do get a fix merged, then please also adjust `package-build--write-pkg-readme` because that contains some code copied from `lm-commentary` for compatibility.

**Comment by Boruch-Baum** [comment] 2021-02-05 01:49
On 2021-02-04 14:19, Jonas Bernoulli wrote:
>    This appears to be a regression in lm-commentary. It would be best to
>    fix it there. If you do get a fix merged, then please also adjust
>    package-build--write-pkg-readme because that contains some code copied
>    from lm-commentary for compatibility.

I see that:

  "lm-commentary is a compiled Lisp function in ‘lisp-mnt.el’.",

and there:

  ;; Author: Eric S. Raymond <esr@snark.thyrsus.com>
  ;; Maintainer: emacs-devel@gnu.org

So I should post a bug report to emacs directly, and reference this issue?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by purcell** [comment] 2021-02-05 07:22
I'd probably just `M-x report-bug` if I were you.

**Comment by Boruch-Baum** [comment] 2021-02-07 14:08
On 2021-02-04 23:22, Steve Purcell wrote:
>    I'd probably just M-x report-bug if I were you.

I just submitted the bug report, to the extent possible for me since I
don't have any first-hand idea what the MELPA software is actually
doing. The bug report is 46364, available here[1]

Two obvious deficiencies in my report are: it lacks the version of
lm-commentary being used by MELPA, and; it lacks any last-known working
version.

refs:
=====
[1] http://debbugs.gnu.org/cgi/bugreport.cgi?bug=46364

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by matta** [comment] 2021-02-09 16:24
This has been fixed in Emacs master (28.0) with http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=9c1e89a32c65244a992a8a1ff73fd606f94a8a15 and I've proposed the same fix to package-build here: https://github.com/melpa/package-build/pull/49

**Comment by Boruch-Baum** [comment] 2021-02-09 16:39
Thanks, Matt.

On 2021-02-09 16:25, Matt Armstrong wrote:
>  This has been fixed in Emacs master (28.0) with
>  ...

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by tarsius** [comment] 2021-02-09 17:24
I've just updated Melpa to use this fix.

Packages won't be rebuild until they have new commits.

**Closed** 2021-02-09 17:25 UTC
