### ISSUE TITLE
A way to figure out what commit a MELPA package was built from?

### ISSUE THREAD

**Issue by glasser** [melpa/melpa#3363] opened 2015-12-06 18:09 UTC
Most of the MELPA packages I use are standard GitHub-fetched packages.

Sometimes the package maintainer merges a PR I care about, and I want to upgrade to it.

I can't figure out any way to tell what git commit was used to create the current version of the MELPA package. I tend to just upgrade and poke at the file manually to see if it has the change in it.

Am I missing some place where the MELPA web interface or metadata available with the package commands shows the git sha corresponding to a given version?

**Comment by milkypostman** [comment] 2015-12-06 22:28
if you look at the version, it's a date; that date is the commit date that the package was built from. so if you look through `git log` you should be able to see the date for which the package exists.

**Comment by milkypostman** [comment] 2015-12-06 22:28
does this help?

**Comment by glasser** [comment] 2015-12-07 00:25
Sure, I get that you can figure out the day, but that's not as fine granularity as a commit. For example, today magit merged a PR I was interested in. I went to the package list and saw that the version number had today's date, so I upgraded... And was disappointed to realize it didn't have the PR yet, and that I couldn't figure out how to tell exactly what it did contain.

**Comment by vyp** [comment] 2015-12-07 00:59
Doesn't the version number also have the hours and minutes?

**Comment by vyp** [comment] 2015-12-07 01:15
@glasser Btw if you want to try things in the latest commits without having to wait for the melpa build to catch up, use [quelpa](https://github.com/quelpa/quelpa). It actually uses melpa's package-build library to build packages locally, so the installation is basically the same as it would have been with a melpa package, *I think...*

You can also install specific commits by specifying it in the recipe by using `:commit` as described [here](https://github.com/milkypostman/melpa#recipe-format), because quelpa uses melpa's recipe format. i.e. just copy the [default melpa recipe](https://github.com/milkypostman/melpa/blob/master/recipes/magit) and just add your appropriate `:commit` label, assuming the commit you want to use works with that recipe.

**Comment by DarwinAwardWinner** [comment] 2015-12-19 16:04
I would find this useful as well. I'm trying to track down which commit of ido-ubiquitous is currently in MELPA, since it doesn't correspond to the current master. There are several commits made on the same day, so I can't tell which one was picked up by MELPA.

**Comment by vyp** [comment] 2015-12-19 16:19
Just realised, the hours and minutes might not be enough because 1) time zones 2) commit time does not correspond to build time (exactly). So while for case 2 the latest commit would the one that's actually built most of the time, melpa could always pick up building of it at an unlucky time.

I see no way to have this information right in emacs itself (apart from say writing a function that diffs all `:files` for each commit in a locally cloned repo to the latest ones in the relevant `~/.emacs.d/elpa/<package>` directory, which is obviously ugly). So I think this will have to be displayed on the melpa.org site itself (via maybe the build process capturing the commit being built somehow).

**Comment by DarwinAwardWinner** [comment] 2015-12-19 16:21
Could the build process add another header item to the elisp file indicating the commit?

**Comment by vyp** [comment] 2015-12-19 16:21
Actually yes that could work, sorry obviously I didn't think about this for more than 2 seconds.

**Comment by vyp** [comment] 2015-12-19 16:26
@DarwinAwardWinner btw for this case with ido-ubiquitous, by looking at the git log and the melpa version at http://melpa.org/#/ido-ubiquitous, it seems to be `3bf3c70`? (pretty sure melpa by default tracks the default branch)

**Comment by DarwinAwardWinner** [comment] 2015-12-19 16:32
@vyp That's odd, master has been at https://github.com/DarwinAwardWinner/ido-ubiquitous/commit/2e826e3f209cb5d2bc92bdbfd3b189d2c06ff51c for weeks. This is an ancestor of the commit MELPA has, so I must have pushed that faulty code, and then quickly realized it was broken and force-pushed a rewind assuming no one had pulled it yet. But I guess MELPA picked it up in that short window. Does MELPA specifically avoid pulling in rewinds of the master branch?

**Comment by vyp** [comment] 2015-12-19 17:04
> Does MELPA specifically avoid pulling in rewinds of the master branch?

Actually I don't even know what melpa does when making a new build (i.e. fresh clone or a git pull or something). However, a git pull will still successfully pull and merge even overwritten history if I recall correctly. I might be wrong though!

I don't understand what you mean when you say master has been at `2e826e3` for weeks? Even if you only merged in `3bf3c70` recently, melpa may have just 'caught up'? (On the melpa.org page it says how long the last build was, and this time it's saying 4 hours.)

---

Anyway, you probably already know this, so sorry to be explicit, but obviously rewriting public history is bad. That's why branches exist (which of course I see you are using), because it means you've made the mistake only in the branch you're developing in. Or if you want to rewind the branch, instead of actually overwriting history, you make a revert commit and then before you merge to master or wherever you want to, you squash away that mistake if you so want. I mean maybe for documentation typos it *could* be understandable/tempting, but even then I wouldn't.

Squashing isn't as destructive as rewriting commits to others observing the branch because it only happens at merge time, at which point you're probably going to delete the branch shortly after anyway.

If you've pushed a mistake commit to master, that's unfortunate but you should really leave it there because you can't really assume *no one* has pulled/cloned in that time (unless maybe you've literally overwritten it within 5-10 seconds or something), at least for a project like ido-ubiquitous which judging by the stars seems to be just about significant enough that you don't have this luxury anymore. (Of course, you can do whatever you want with your project and just warn your users about it, but it doesn't instil confidence.)

Although at the same time most elisp projects don't really have the complexity to warrant a robust branch based development system in the first place, so weigh pros vs cons as appropriate.

**Comment by DarwinAwardWinner** [comment] 2015-12-19 18:30
`git pull` is basically a shortcut for `git fetch` followed by `git merge`, so it won't follow a `git reset --hard` to a previous commit, which is essentially what I did. (At least, I think I did. Like I said, I don't remember exactly what I pushed in what order on a specific day 3 weeks ago.) In any case, I suppose I'll avoid rewinding master in the future, even if I only pushed it for a few seconds.

**Comment by vyp** [comment] 2015-12-19 19:17
Yep I just tried it, you're right, I was wrong about git pull. :open_mouth: More reason to avoid rewriting history. As in, you can rewrite local unpushed commits as much as you want, but treat them as unchangeable once pushed. (Of course, there's always edge cases such as when needing to use `git-filter-branch` or something.)

**Comment by DarwinAwardWinner** [comment] 2015-12-19 19:23
Is `git pull` what MELPA uses when updating its copy of each package's repo? I kind of assumed that it would always follow the source repo's master branch wherever it goes i.e. essentially `git fetch; git reset --hard origin/master`.

**Comment by vyp** [comment] 2015-12-19 19:45
@DarwinAwardWinner Nope I think it uses what you said, `git fetch` and then `git reset --hard`.

**Comment by DarwinAwardWinner** [comment] 2015-12-19 19:49
Weird. I wonder how it got stuck on 3bf3c70 then. My repo was briefly on 3bf3c70 on November 29th, before I did a hard reset back to 2e826e3 on the same day, and have left master at 2e826e3 until today, and yet MELPA has been using 3bf3c70 for these 3 weeks. 

(Not sure if I should open a new issue for this.)

**Comment by vyp** [comment] 2015-12-19 19:57
@DarwinAwardWinner oh it's *been* on `3bf3c70` for the past few weeks. I think it's because it compares against the latest commit time or something. Which means it had the newer `3bf3c70` version, saw that `2e826e3` is older in time, and decided to not build it. Furthermore, I think this might be a package.el thing rather than package-build.el (??) because I do recall similar issues with quelpa, though I'm not sure it was exactly the same scenario. I think there were even similar issues here about this but don't have time to track any down right now. I'm only guessing from my bad memory though, @purcell would probably know for sure.

**Comment by vyp** [comment] 2015-12-20 08:08
I can't find any similar issues to this on melpa, but I did find this: https://github.com/quelpa/quelpa/issues/82#issuecomment-128648791. Which seems to suggest I was right about it comparing the time of the installed one vs the git commit date somehow, which may be why it stayed on `3bf3c70` instead of going back to `2e826e3`.

**Comment by milkypostman** [comment] 2015-12-29 06:32
@vyp @DarwinAwardWinner so the issue is that we don't overwrite packages unless they are newer. i.e., if you commit something today, then hard reset+force push to a previous build day, then MELPA will be stuck on the newer one. i need to fix this i think. 

iiuc it's bad form to force push to a master branch (or a branch that others have pulled from).

**Comment by vyp** [comment] 2015-12-29 06:48
Actually the original issue was to be able to know what commit a melpa package was built from.

**Comment by purcell** [comment] 2015-12-29 07:50
Yep, I think we should keep this open for the original issue, but I'd be keen to receive a PR for this because I don't currently have much time to jump in and implement it.

**Comment by vyp** [comment] 2015-12-29 08:17
> I don't currently have much time to jump in and implement it.

I probably would have tried something by now, but alas the same. :( Not for a while I think.

**Comment by DarwinAwardWinner** [comment] 2015-12-30 04:24
If someone can point me to the right file, I can take a crack at it tomorrow.

**Comment by purcell** [comment] 2015-12-30 08:53
@DarwinAwardWinner It'd just be in `package-build.el` -- the various checkout functions would need to (optionally) return commits identifiers in addition to versions, then those commit identifiers would need to be inserted into each package descriptor (`archive-contents` element) as an additional custom key/value pair.

**Comment by tarsius** [comment] 2017-03-12 11:08
I've assigned this to myself as a way to keep track of it. This does not necessarily mean I will do something.

**Comment by vermiculus** [comment] 2017-05-06 20:05
My recommendation would be to throw the SHA after the source at [`melpa.js:408`](https://github.com/melpa/melpa/blob/master/html/js/melpa.js#L408). You'd have to push it onto the object at [L150](https://github.com/melpa/melpa/blob/master/html/js/melpa.js#L150), but it's probably easier to throw it in `props`.

**Comment by vermiculus** [comment] 2017-05-06 20:58
Once the above issue is resolved, should I make the PR against melpa/package-build instead? This repo's README states that we grab it using subtree.

I won't be able to implement its pair in that repository though, so it'd be two separate PRs.

**Comment by purcell** [comment] 2017-05-06 23:39
> Once the above issue is resolved, should I make the PR against melpa/package-build instead? This repo's README states that we grab it using subtree.

Yes please.

**Comment by purcell** [comment] 2017-05-06 23:42
> My recommendation would be to throw the SHA after the source at melpa.js:408. You'd have to push it onto the object at L150, but it's probably easier to throw it in props.

Yes, probably an entry called "commit" in props.

**Comment by vermiculus** [comment] 2017-05-06 23:53
Will do 😄

Also, [`:commit` is exactly what will be used](https://github.com/vermiculus/melpa/commit/82dd3b4f53946a06412bc45993251191d4ad4c6e#diff-041545550faf9bc6ac167f4c94fa20a8R1304) 😉

**Closed** 2017-05-07 03:28 UTC
Labels: feature

**Comment by glasser** [comment] 2017-09-29 00:09
I sent a patch to Emacs itself to display the commit in the package description.
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28637

**Comment by glasser** [comment] 2017-10-10 05:48
I sent that patch to Emacs 1.5 weeks ago and it didn't get any sort of response. Is that typical?

**Comment by tarsius** [comment] 2017-10-10 07:09
It can happen - you will have to ping.

**Comment by glasser** [comment] 2017-10-10 07:19
Do I ping on bug-gnu-emacs or emacs-devel?

**Comment by tarsius** [comment] 2017-10-10 07:27
I'm not sure, I would think its best to first ping on the issue and only escalate to emacs-devel if necessary.

I am only somewhat familiar with the `package.el` code. Does this information get stored with/for the installed package version? I assume that when a new version becomes available it is still possible to get the `commit` of the installed version. How would I do that from outside `package.el` (say in `magit-version`)?

**Comment by glasser** [comment] 2017-10-10 19:35
I'm not super clear either — it looks like this is in the files in `~/.emacs.d/elpa/archives`.
