### ISSUE TITLE
How to report a broken dependency regarding the currently available version of a package

### ISSUE THREAD

**Issue by gixxi** [melpa/melpa#5760] opened 2018-10-17 15:12 UTC
I observed a broken depencency of CIDER 0.18.0 with regard to sesman 0.3.2

in sesman there a recent fix

https://github.com/vspinu/sesman/commit/14475d8192a785568a23f274f7715b1509da93ea

that causes a fresh emacs 25 installation using CIDER 0.18.0 to fail to connect to a Clojure REPL.

This was fixed in CIDER also most recently

https://github.com/clojure-emacs/cider/commit/23de90cf771a236b424eb3fa8a4403041bed2e40

but from my perspective the later change is not reflected in the Melpa Repo.

Thanks
Christian

**Comment by milkypostman** [comment] 2018-10-17 16:16
We’ve had issues with updates not happening. I’ll check it out later this
evening. Sorry for the inconvenience.

**Comment by milkypostman** [comment] 2018-10-30 02:54
the actual commit for the change was done on october 17. and the problem is that as hard as we try, package-build cannot seem to uncover from git the *actual* merge date. I worked on this problem a lot a long time ago -- there is a bug floating around here somewhere about it -- but there wasn't an elegant solution that i could find.

regardless of this the problem has resolved itself and the fix is in according to my investigation.

i am sorry that it took me so long to respond as quickly as i had hoped. things got hectic and i didn't have access to my machine.

**Closed by milkypostman** 2018-10-30 02:54 UTC
