### ISSUE TITLE
Yasnippet build doesn't seem to have dropped snippets dir, even though upstream repo has

### ISSUE THREAD

**Issue by npostavs** [melpa/melpa#5225] opened 2018-01-05 14:22 UTC
Hi, I've recently removed the yasnippet-snippet submodule from the yasnippet repo, but the MELPA package still has the snippets. I can see that the code in the MELPA installed package does have the latest change (joaotavora/yasnippet@04062d8b4f7391069058345e1efd673add0357f8), so it's not an issue of simply waiting a bit for MELPA to catch up.

The relevant commit is joaotavora/yasnippet@b1ca2197062340d4c9e78442ea38957a96f968d4 (github unhelpfully shows only the author date, the commit date is `Mon Jan 1 15:11:55 2018 -0500`).

Does MELPA reuse git checkouts across builds? Perhaps the submodules need to be deconfigured/removed manually?

**Comment by milkypostman** [comment] 2018-01-05 20:19
Your explanation is probably the cause. I’ll try to get to this in the next couple of days if someone else doesn’t.  Thanks for reporting.

**Comment by milkypostman** [comment] 2018-01-11 21:41
i removed any extra directories and rebuilt. may take a while to update but should be fixed now.

**Closed by milkypostman** 2018-01-11 21:41 UTC

**Comment by npostavs** [comment] 2018-01-12 13:31
Thanks, I can confirm `yasnippet-20180111.1533` no longer has a snippets directory.
