### ISSUE TITLE
Need help getting multi-directory package GNU Hyperbole on MELPA

### ISSUE THREAD

**Issue by rswgnu** [melpa/melpa#6987] opened 2020-06-24 19:21 UTC
GNU Hyperbole is presently available as a package only from GNU ELPA when formal releases are made.  Source versions are available on Github  (see www.github.com/rswgnu/hyperbole) but we would like these more recent versions to be installable as a package from MELPA, as formal releases are infrequent now.  The problem is that the package contains a second subdirectory of Emacs Lisp code that must be maintained in place, kotl/, and Info files are in another subdirectory, man/.

Is there someone on the project who could help us develop the recipe for Hyperbole to get it onto MELPA?  Timewise, sometime this week would be ideal.

**Comment by milkypostman** [comment] 2020-06-29 01:27
So the Elisp lives as part of the entire project repo?

There are other packages that do this but it’s not ideal because it means
pulling down a lot of unnecessary files. It’s be nice to have them in a
separate repo. Is there a reason this couldn’t be done?

 If you read the recipe format you can list files in any directory.

**Comment by tarsius** [comment] 2020-07-04 13:20
> The problem is that the package contains a second subdirectory of Emacs Lisp code that must be maintained in place, kotl/, and Info files are in another subdirectory, man/.

You probably want `:files (:defaults "kotl" "man")`. Or maybe you don't want the directories but the contents of these files. In any case I recommend you read the documentation and also test whether the recipe you come up with works as intended.

https://github.com/melpa/melpa#recipe-format
https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#test-your-recipe

> There are other packages that do this but it’s not ideal because it means pulling down a lot of unnecessary files.

This does not apply here. This particular repository doesn't contain any stuff that would better be maintained in a separate repository.

**Comment by rswgnu** [comment] 2020-07-04 17:14
Thanks, Jonas.  Will give it a try when I get a chance.  -- Bob

**Comment by tarsius** [comment] 2020-11-17 11:23
Closing this and looking forward to a pull-request. ;P

**Closed by tarsius** 2020-11-17 11:23 UTC
