### ISSUE TITLE
The build of melpa is stopping?

### ISSUE THREAD

**Issue by masasam** [melpa/melpa#5395] opened 2018-03-29 00:13 UTC
I've pushed my package to melpa two days ago.
But package has not been updated.
Other packages also don't seem to be updated.
Please check it.

**Comment by milkypostman** [comment] 2018-03-29 00:26
Which package?

**Comment by masasam** [comment] 2018-03-29 01:18
Thank you for your reply.
https://melpa.org/#/easy-hugo
https://melpa.org/#/easy-jekyll

**Comment by masasam** [comment] 2018-03-29 12:13
@milkypostman Thanks!

**Comment by masasam** [comment] 2018-03-30 01:32
MELPA is OK,
but MELPA Stable Packages isn't update.
Please check it.

**Comment by milkypostman** [comment] 2018-03-30 04:32
Yeah. I'll fix it up. Soon

**Comment by jgkamat** [comment] 2018-03-31 02:34
When trying to build any recipes with valid stable builds locally, I get the following error:

```
*[j@laythe melpa]$ STABLE=t make recipes/magit
 • Building package magit ...
Package: magit
Fetcher: github
Source:  https://github.com/magit/magit.git

Updating /home/jay/Code/tmp/melpa/working/magit/
No valid stable versions found for magit
Makefile:102: recipe for target 'recipes/magit' failed
make: [recipes/magit] Error 255 (ignored)
```

I think this is causing this issue. Because of this, the new release of magit is [not making it to melpa stable](http://stable.melpa.org/#/magit). It's 2.11 right now, and the latest version is 2.12.

I did a bisect, and I think the first bad commits are c1e6b7a8 and/or 01b2b665.

Unfortunately, the changes are much to complicated for me to understand, so I don't think I can debug it any further.

Please let me know if I can help in any other way on my end though.

[cc @tarsius]

**Comment by tarsius** [comment] 2018-03-31 03:33
I've pushed a fix.

**Comment by jgkamat** [comment] 2018-03-31 03:55
Thanks, master looks good to me now! Hopefully, I'll be able to pull magit 2.12 on the next build :heart:

**Comment by milkypostman** [comment] 2018-03-31 03:57
I didn’t have time to update the stable melpa server yet. I suspect it will have the old version of emacs problem. I have been traveling home all day so I will do my best to address it first thing tomorrow morning. 

Very sorry for the delay.

**Comment by tarsius** [comment] 2018-03-31 15:13
And I am sorry for the regressions I have introduced.

**Comment by milkypostman** [comment] 2018-03-31 15:16
it's all good. i am updating the server now, things will be working
properly again soon.

**Comment by milkypostman** [comment] 2018-03-31 16:41
stable is fixed.

**Closed by milkypostman** 2018-03-31 16:42 UTC
