### ISSUE TITLE
w3m-load.el is missing in melpa#w3m

### ISSUE THREAD

**Issue by yamaoka** [melpa/melpa#6435] opened 2019-09-13 07:38 UTC
Hi,
Sorry in advance if I mistake the place to write this.

Recently it was reported[1] by a user of melpa#w3m[2] that `M-x report-emacs-w3m-bug` does not work because of an error. 　 The reason it occurs is that there is no `w3m-load.el` file in melpa#w3m. 　 The file will be created when building, i.e., performing `make`, emacs-w3m in a local copy of the original emacs-w3m git repository[3]. 　 It contains some autoloads and the `emacs-w3m-git-revision` constant that holds the revision hash value of the latest commit in the original emacs-w3m git repository.

(Embedding the revision hash in a bug report will make it easy to know what version of emacs-w3m a user uses. 　 So, the value should be the one based on the original git repo, or a timestamp that says when it was done in the original git repo, etc.)

Since embedding some kind of ID in a file registered in the git repo when committing will arise the chicken and the egg problem, so I think there is no way to know the ID other than in a checked out copy. 　 Isn't it possible to make the melpa#w3m builder run `make` in a copy of the original emacs-w3m git repo in order to create the w3m-load.el file?

Thanks in advance.
Regards,

[1] http://emacs-w3m.namazu.org/ml/msg13434.html
[2] https://melpa.org/#/w3m
[3] https://github.com/emacs-w3m/emacs-w3m

**Comment by dickmao** [comment] 2019-09-13 13:14
There are several ways to go about this.  The easiest is to gate `emacs-w3m-git-revision` with an fboundp check and apologize to the user.  Perhaps the most brutal (but thorough) is as follows:

1. Add `.git` to w3m's melpa recipe
2. Add `(eval-when-compile (autoload 'w3mhack-generate-load-file "w3mhack") (w3mhack-generate-load-file))` to `w3m.el`

> Isn't it possible to make the melpa#w3m builder run make in a copy of the original emacs-w3m

Alas, no.

**Comment by purcell** [comment] 2019-09-14 01:48
`*-load.el` files are hacky solutions for situations where the source code it is just copied into a directory on the `load-path`. "Proper" installation, whether via a "make" process or `package.el`, involves generating an autoload file using the facilities of the running Emacs process. So the right solution here is to add appropriate `;;;###autoload` cookie comments in the `w3m` source: then a `w3m-autoloads.el` file will be generated by `package.el` at installation time, and then loaded at initialisation time in future.

**Comment by purcell** [comment] 2019-09-14 01:50
Regarding the git revision, that is redundant when installing from `package.el`, because the package metadata will contain this revision anyway, so the w3m code should treat it as optional in order to support different installation methods.

**Comment by yamaoka** [comment] 2019-09-18 06:58
Thank you all, but I made a change so to make emacs-w3m create the w3m-load.el file if it is missing in the melpa installation after all, and changed the recommended recipe for getting started emacs-w3m as shown in this page:

https://emacs-w3m.github.io/index.html#configuration

I picked up the revision hash of the original git repo from the "~/.emacs.d/elpa/archives/melpa/archive-contents" file (if exists). 　 Since it will not necessarily always be correct, the program will prompt a user to update the installation if the timestamp picked from the file and the installation directory name are mismatched.

Regards,

**Comment by tarsius** [comment] 2019-09-29 20:11
@purcell Are you okay with this? https://github.com/emacs-w3m/emacs-w3m/compare/efa37f71%5E..c9090aaf

**Comment by purcell** [comment] 2020-01-21 23:00
Only saw this now, sorry.

> @purcell Are you okay with this? https://github.com/emacs-w3m/emacs-w3m/compare/efa37f71%5E..c9090aaf

No. I can't really understand why this bizarre approach has been taken insteads of just setting up the `;;;###autoload` cookies appropriately and allowing the usual autoload generation process to do the right thing.

**Comment by purcell** [comment] 2020-01-21 23:07
Reopening to keep track of this, because it needs to be resolved.

**Comment by yamaoka** [comment] 2020-01-22 01:51
Because we needed to embed the git revision number in an .el file for a certain reason.　Autoloading is not a main matter.

**Comment by purcell** [comment] 2020-01-22 02:13
> Because we needed to embed the git revision number in an .el file for a certain reason.　Autoloading is not a main matter.

Can you explain more? I'd be happy to help advise you on a more appropriate solution. For instance, you could potentially obtain the git revision from the MELPA metadata, or we could even start including the revision as a header in the package so your code could extract it.

Generating and byte-compiling a `w3m-load` file using all this MELPA-specific hackery is not viable. The only reason to distribute a `-load.el` file is for people who cannot generate autoloads themselves, and it should absolutely not be necessary here.

**Comment by yamaoka** [comment] 2020-01-22 02:42
Wasn't the first message I posted here enough to explain?

cf. https://github.com/melpa/melpa/issues/6435#issue-493179861

**Comment by purcell** [comment] 2020-01-22 07:13
> Wasn't the first message I posted here enough to explain?

Yes, it explains the intent, but the solution is inappropriate:

- Creating and byte-compiling extra files at load time is unsafe and error prone
- The given solution does not work for MELPA Stable or if the user has chosen a different name for the MELPA archive
- There's no guarantee that `package-archives` contains information about the currently-installed `w3m` package
- In any case, packages shouldn't contain code that takes different paths according to how it was installed

I understand that you want:

1. A `-load.el` file for autoloads
2. To know what the git revision is for the currently-installed package

The two have been combined here in an unnecessary way. `w3m` should work without `w3m-load.el`: generating `w3m-autoloads.el` should cover point 1.

Handling point 2 (the git revision) is separate. I think that when `w3c` is installed via MELPA, you can determine the git revision *at runtime* if necessary by looking at the generated `w3c-pkg.el` file in the same directory as `w3c.el` -- this contains a `:commit` entry.

It should not be necessary to generate a `w3c-load.el` file at runtime if the git revision can also be determined at runtime.

**Comment by yamaoka** [comment] 2020-01-22 07:56
> Handling point 2 (the git revision) is separate. I think that when w3c is installed via MELPA, you can determine the git revision at runtime if necessary by looking at the generated w3c-pkg.el file in the same directory as w3c.el -- this contains a :commit entry.

If you meant w3m, not w3c, there's no :commit entry in w3m-pkg.el.　Is there a way to add such an entry?　Otherwise, if the w3c package really exists and it does a way something smart, I really want to know how it does it.　That's really great!

**Comment by purcell** [comment] 2020-01-22 09:09
Haha, no, I meant "w3m" sorry. I'll have a look at how the `w3m-pkg.el` is getting generated and will respond later. :-)

**Comment by tarsius** [comment] 2020-11-17 11:49
@yamaoka have you seen this commit, 76487a2bb14f03832f1fb7ae0106c180d4871950?

@purcell would you mind giving him some guidance again, please?

**Comment by yamaoka** [comment] 2020-11-17 22:22
I don't keep track every git repository, sorry.  Where was the
76487a2 commit done, and what did it achieve?

Apart from it, five months ago, I noticed the w3m-pkg.el file to
have gotten to hold the git commit hash, and modified emacs-w3m
so to use it to know the hash value (revno: d0c12f3).

**Comment by tarsius** [comment] 2020-11-17 23:08
Ah sorry I meant https://github.com/melpa/package-build/commit/76487a2bb14f03832f1fb7ae0106c180d4871950, which is how w3m-pkg.el got hold of the commit hash. :grin:

**Comment by yamaoka** [comment] 2020-11-18 00:51
I see.  Thanks.  The change caused just what I found in
w3m-pkg.el five month ago.

Currently the w3m melpa package uses that :commit value as that
of the constant `emacs-w3m-git-revision'.  It is incorporated to
the file w3m-load.el (of which the most contents are the ones
copied from the w3m-autoloads.el file).  Why we create the file
w3m-load.el are that the melpa package doesn't do it, and:

・For two decades, it has been being created when a user builds
　and installs emacs-w3m from the source.
・We have been recommending a user to load the w3m-load.el file.
　For instance, see: <https://emacs-w3m.github.io/#configuration>
・We don't want to make a user confused by an additional
　description like: If you are a melpa user, don't try to load
　w3m-load.el.

**Comment by tarsius** [comment] 2020-11-19 19:31
I think you can replace your hack with this now:

```elisp
(defvar emacs-w3m-git-revision "unknown"
  "Use the function by same name instead.")
(make-obsolete-variable
 'emacs-w3m-git-revision
 "use the function by same name instead"
 "0.0.0") ; TODO This should be the next release.

(defun emacs-w3m-git-revision ()
  "Return the Git revision string of this package."
  (or (ignore-errors
        (cdr (assq :commit
                   (package-desc-extras (cadr (assq 'w3m package-alist))))))
      "unknown"))
```

**Comment by yamaoka** [comment] 2020-11-19 22:12
Ok.　Thanks.　So, do you have an idea how we do it for users who
build emacs-w3m using the source obtained directly from the git
repository?　Note that there is no w3m-pkg.el file containing
the :commit value in that case.　As far as I can tell, there is
no way to embed the latest git revision hash value in a file in
the repository.　This is why we designed emacs-w3m so to
generate a file, i.e., w3m-load.el, containing the hash value
when building emacs-w3m.

**Comment by tarsius** [comment] 2020-11-19 23:22
```elisp
(defun emacs-w3m-git-revision ()
  "Return the Git revision string of this package."
  (or (ignore-errors
        (cdr (assq :commit
                   (package-desc-extras (cadr (assq 'w3m package-alist))))))
      (ignore-errors
        (let ((default-directory (file-name-directory (locate-library "w3m"))))
          (car (process-lines "git" "rev-parse" "HEAD"))))
      "unknown"))
```

**Comment by yamaoka** [comment] 2020-11-20 00:28
Unfortunately, the directory where emacs-w3m is installed is not necessarily a git copy.

**Comment by tarsius** [comment] 2020-11-20 09:53
Ah right forgot about that common case (it was late). Well to deal with that case I recommend generating a file during installation. Here is how magit stores the version in a file during installation. You could do something similar.

```Makefile
VERSION ?= $(shell \
  test -e $(TOP).git && \
  git describe --tags --abbrev=0 --always | cut -c2-)

$(PKG)-version.el:
	@printf "Generating $@\n"
	@printf "%s" "$$VERSIONLIB_TMPL" > $@

define VERSIONLIB_TMPL
;;; $(PKG)-version.el --- the Magit version you are using

(setq $(PKG)-version "$(VERSION)")

(provide '$(PKG)-version)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; $(PKG)-version.el ends here

endef
export VERSIONLIB_TMPL
#'
```

And for the sake of full disclosure, magit is actually using something somewhat similar to what you are doing. See `magit-version`. But I cannot say that worked out well in practice. It was intended to make debugging easier, the result was that it itself had to be debugged many times (which is why it collects debug information about what methods it tried). Nowadays it works fairly well, but I recommend you don't go down road, it simply is not worth the effort.

**Comment by yamaoka** [comment] 2020-11-23 23:02
> but I recommend you don't go down road, it simply is not worth
> the effort.

I think so, too.  Actually the situation where the embedded git
hash is usefull has never happend so far, so we don't have a
will to improve it further, and also to spend time to remove it.

Thanks.

**Comment by tarsius** [comment] 2020-11-24 09:53
Let's close this again then.

**Closed by tarsius** 2020-11-24 09:53 UTC
Labels: recipes
