### ISSUE TITLE
Cannot find package elgrep

### ISSUE THREAD

**Issue by TobiasZawada** [melpa/melpa#6254] opened 2019-07-01 13:08 UTC
Andreas Roehler informed me in https://github.com/TobiasZawada/elgrep/issues/4 that installing elgrep via `package-install` fails.

I tried to build the recipe `make recipes/elgrep` and got the following error:

```
~/tmp/melpa $ make recipes/elgrep
 • Building recipe elgrep ...
/usr/bin/timeout -k 60 600 emacs --no-site-file --batch -L .//package-build -l package-build.el --eval "(let ((package-build-stable nil) (package-build-write-melpa-badge-images t) (package-build-archive-dir (expand-file-name \"./packages\" package-build--melpa-base))) (package-build-archive \"elgrep\"))"
Cannot find package elgrep
Makefile:93: recipe for target 'recipes/elgrep' failed
make: [recipes/elgrep] Error 255 (ignored)
 ✓ Wrote  28K -rwxrwxrwx 1 toz toz 28K Feb 27  2018 ./packages/elgrep-20180227.1119.el
   0 -rwxrwxrwx 1 toz toz 362 Feb 27  2018 ./packages/elgrep-20180227.1119.entry
 28K -rwxrwxrwx 1 toz toz 28K Mar  2  2018 ./packages/elgrep-20180302.1427.el
   0 -rwxrwxrwx 1 toz toz 362 Mar  2  2018 ./packages/elgrep-20180302.1427.entry
4.0K -rwxrwxrwx 1 toz toz 968 Mar  2  2018 ./packages/elgrep-badge.svg
   0 -rwxrwxrwx 1 toz toz 439 Mar  2  2018 ./packages/elgrep-readme.txt 
 Sleeping for 0 ...
sleep 0
```

My questions: 

- Why does Melpa not use the latest git-version?
- Why can the packge not be found?  What can I do about it?

I run the quality-checking tools. `flycheck-package` says it would not find the package `async.el` but I added it to the dependencies with version string "1.5". It should work, shouldn't it?

Otherwise there are no indications for quality issues.

**Comment by riscy** [comment] 2019-07-14 16:19
Just trying to reproduce this -- if I run a file that contains `(package-install 'elgrep)`:
```
Contacting host: melpa.org:80
Generating autoloads for elgrep.el...
Generating autoloads for elgrep.el...done
Wrote /root/.emacs.d/elpa/elgrep-20190701.1207/elgrep-autoloads.el
Wrote /root/.emacs.d/elpa/elgrep-20190701.1207/elgrep-autoloads.el
Checking /root/.emacs.d/elpa/elgrep-20190701.1207...
Compiling /root/.emacs.d/elpa/elgrep-20190701.1207/elgrep-autoloads.el...
Compiling /root/.emacs.d/elpa/elgrep-20190701.1207/elgrep-pkg.el...
Compiling /root/.emacs.d/elpa/elgrep-20190701.1207/elgrep.el...
Done (Total of 1 file compiled, 2 skipped)
```

This is installing the latest version with the `async.el` dependency you recently updated, so I think it's fixed?

**Comment by conao3** [comment] 2019-07-14 16:22
Maybe original issue author just mistakes MELPA URL (dropped the last slash of the MELPA URL?).

**Comment by andreas-roehler** [comment] 2019-07-14 16:56
On 14.07.19 18:22, Naoya Yamashita wrote:
>
> Maybe original issue author just mistakes MELPA URL (dropped the last 
> slash of the MELPA URL?).
>
Started from emacs -Q

loading:

(require 'package)
(add-to-list 'package-archives
              '("melpa" . "https://melpa.org/packages") t)
(package-initialize)

Still getting "not found". See report below and png attached.

Best,
Adnreas

In GNU Emacs 26.2 (build 1, i686-pc-linux-gnu, GTK+ Version 3.14.5)
  of 2019-04-02

Windowing system distributor 'The X.Org Foundation', version 11.0.11604000
System Description:    Debian GNU/Linux 8.11 (jessie)

Recent messages:
Type C-x 1 to delete the help window, C-M-v to scroll help.
mouse-2, RET: Push this button [5 times]
Install package ‘elgrep-20190518.1539’? (y or n) y
Setting ‘package-selected-packages’ temporarily since "emacs -q" would 
overwrite customizations
Contacting host: melpa.org:443
package-install-from-archive: 
https://melpa.org/packageselgrep-20190518.1539.el: Not found
<print> is undefined
Install package ‘elgrep-20190518.1539’? (y or n) y
Contacting host: melpa.org:443
package-install-from-archive: 
https://melpa.org/packageselgrep-20190518.1539.el: Not found
Quit
Configured using:
  'configure --with-modules --with-mailutils'

Configured features:
XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS
LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES
THREADS

Important settings:
   value of $LANG: de_DE.utf8
   locale-coding-system: utf-8-unix

Major mode: Help

Minor modes in effect:
   tooltip-mode: t
   global-eldoc-mode: t
   electric-indent-mode: t
   mouse-wheel-mode: t
   tool-bar-mode: t
   menu-bar-mode: t
   file-name-shadow-mode: t
   global-font-lock-mode: t
   font-lock-mode: t
   blink-cursor-mode: t
   auto-composition-mode: t
   auto-encryption-mode: t
   auto-compression-mode: t
   buffer-read-only: t
   line-number-mode: t
   transient-mark-mode: t

Load-path shadows:
None found.

Features:
(shadow sort mail-extr emacsbug sendmail lisp-mnt help-mode mm-archive
message dired dired-loaddefs format-spec rfc822 mml mml-sec epa derived
gnus-util rmail rmail-loaddefs mailabbrev gmm-utils mailheader mm-decode
mm-bodies mm-encode mail-utils cus-edit cus-start cus-load wid-edit
network-stream starttls url-http tls gnutls mail-parse rfc2231 rfc2047
rfc2045 mm-util ietf-drums mail-prsvr url-gw nsm rmc puny url-cache
url-auth url url-proxy url-privacy url-expand url-methods url-history
url-cookie url-domsuf url-util mailcap epg finder-inf rx info package
easymenu epg-config url-handlers url-parse auth-source cl-seq eieio
eieio-core cl-macs eieio-loaddefs password-cache url-vars seq byte-opt
gv bytecomp byte-compile cconv cl-loaddefs cl-lib misearch multi-isearch
vc-filewise vc-rcs elec-pair time-date mule-util tooltip eldoc electric
uniquify ediff-hook vc-hooks lisp-float-type mwheel term/x-win x-win
term/common-win x-dnd tool-bar dnd fontset image regexp-opt fringe
tabulated-list replace newcomment text-mode elisp-mode lisp-mode
prog-mode register page menu-bar rfn-eshadow isearch timer select
scroll-bar mouse jit-lock font-lock syntax facemenu font-core
term/tty-colors frame cl-generic cham georgian utf-8-lang misc-lang
vietnamese tibetan thai tai-viet lao korean japanese eucjp-ms cp51932
hebrew greek romanian slovak czech european ethiopic indian cyrillic
chinese composite charscript charprop case-table epa-hook jka-cmpr-hook
help simple abbrev obarray minibuffer cl-preloaded nadvice loaddefs
button faces cus-face macroexp files text-properties overlay sha1 md5
base64 format env code-pages mule custom widget hashtable-print-readable
backquote threads dbusbind inotify dynamic-setting system-font-setting
font-render-setting move-toolbar gtk x-toolkit x multi-tty
make-network-process emacs)

Memory information:
((conses 8 1238999 144371)
  (symbols 24 51122 1)
  (miscs 20 61 272)
  (strings 16 217144 27926)
  (string-bytes 1 4331137)
  (vectors 12 37676)
  (vector-slots 4 806626 29550)
  (floats 8 65 231)
  (intervals 28 137243 220)
  (buffers 536 15)
  (heap 1024 65779 12886))

**Comment by conao3** [comment] 2019-07-14 16:59
Yes, you dropped the last slash of MELPA URL. see MELPA readme.

>Then just use M-x package-list-packages to browse and install packages from MELPA and elsewhere.
Note that you'll need to run M-x package-refresh-contents or M-x package-list-packages to ensure that Emacs has fetched the MELPA package list before you can install packages with M-x package-install or similar.
Instead of the messy code above, you can of course use something like the following instead:

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
```

**Comment by andreas-roehler** [comment] 2019-07-14 17:09
Okay, thanks, works now.

**Comment by conao3** [comment] 2019-07-14 17:09
OK, Good.

**Comment by riscy** [comment] 2019-07-14 17:32
Thanks @canao3.  I'll close this.

**Closed by riscy** 2019-07-14 17:32 UTC

**Comment by TobiasZawada** [comment] 2019-07-16 17:36
Thank you to all who helped to clarify the problem!

Best regards,
Tobias
