### ISSUE TITLE
Keep old versions on Melpa-stable ?

### ISSUE THREAD

**Issue by xuchunyang** [melpa/melpa#3948] opened 2016-05-31 17:01 UTC
It looks like Melpa-stable doesn't keep old versions, for example, I can download latest version v1.9.6 of helm from http://stable.melpa.org/packages/helm-1.9.6.tar but I cannot download v1.9.5 from http://stable.melpa.org/packages/helm-1.9.5.tar

Keeping old versions will make it possible to install a specific version of some package, though `package.el` doesn't support install old versions yet.  GNU Elpa and Org Elpa keep old versions
- http://elpa.gnu.org/packages/seq.html (taking `seq.el` as an example)
- http://orgmode.org/elpa/

Just keeping package tarball (or single elisp) file is not enough, I think we should also keep accompanying package description, use v1.9.6 of helm as example

``` el
(helm . [(1 9 6)
         ((emacs (24 3)) (async (1 9)) (popup (0 5 3)) (helm-core (1 9 6)))
         "Helm is an Emacs incremental and narrowing framework"
         tar
         ((:url . "https://emacs-helm.github.io/helm/"))])
```

maybe save it in `helm-1.9.6.entry` for now, with this file, we will know package's name, version, dependency and exact dowload url (that is, `xxx/helm-1.9.6.tar`).

**Comment by purcell** [comment] 2016-06-03 06:03
I agree that this would be a nice change. It's quite a lot of work right now, I think.

**Comment by purcell** [comment] 2017-05-18 09:48
Duplicate of #4712: I'll keep that issue open and close this.

**Closed by purcell** 2017-05-18 09:48 UTC
Labels: feature
