### ISSUE TITLE
Is it possible to publish Emacs 25.1+ modules?

### ISSUE THREAD

**Issue by vermiculus** [melpa/melpa#4321] opened 2016-10-15 18:23 UTC
Obviously the build process is very different – even unpredictable. How should packages with module dependencies go about expressing and resolving those dependencies?

**Comment by purcell** [comment] 2016-10-15 23:58
I'm not sure I understand your question, sorry. If your package requires Emacs 25.1+, then you should depend on that Emacs version. Generally you wouldn't specify dependencies on specific modules that are shipped with Emacs unless they are also installable independently in lower Emacs versions -- examples include `seq` and `cl-lib`. Is that what you were getting at?

**Comment by vermiculus** [comment] 2016-10-16 00:20
Sorry – I was under the impression that 'packages' referred to emacs lisp programs and 'modules' referred to C shared objects that emacs can load as of 25.1. These must be built with `make` or similar systems.

**Comment by purcell** [comment] 2016-10-16 01:08
Oh, I see. Yeah, no idea how that is supposed to work. Perhaps it has been discussed on the emacs list.

**Comment by tarsius** [comment] 2016-10-21 15:13
I think you will have to do the same thing as `emacsql` (start by looking at `emacsql-sqlite-prompt`). In the lisp part detect whether the C module exists and is up-to-date, and if that is not the case, then ask the user whether s/he wants to download the compiled module or build it him/herself.

**Comment by lunaryorn** [comment] 2016-10-21 15:37
Or compile on the fly—in a language with good dependency management that's a feasible option imho.

I'm writing a rust interface for modules with that approach.

**Comment by tarsius** [comment] 2016-10-21 19:28
Yes, agreed. I didn't actually mean that the user should be told to "now go and do this manually" more like "should I compile this for you?". The problem is that the user might not have a compiler installed. Giving the user the *option* to use a pre-compiled module seems like a good compromise.

**Comment by purcell** [comment] 2016-10-21 23:48
Closing because this isn't something MELPA can solve, but please feel free to continue discussing here if that's helpful.

**Closed by purcell** 2016-10-21 23:48 UTC

**Comment by marsam** [comment] 2017-02-26 23:33
Hi:

FWIW I was thinking a way to distribute emacs modules. Sorry for the noise.

`define-package` from `{project-name}-pkg.el` accept an `extras` plist, which is currently unused, I think we can add a build description in there in the same way as `luarocks` or `opam`.

And for the build process, I think we need to patch `package-install-from-archive` to execute the compilation process and forward it to upstream.

I'll try to make a demo these days.

For reference LuaRocks build spec:

```lua
-- from: https://github.com/brimworks/lua-http-parser/blob/master/lua-http-parser-scm-0.rockspec
-- ...
build = {
    type = 'cmake',
    variables = {
        INSTALL_CMOD      = "$(LIBDIR)",
        CMAKE_BUILD_TYPE  = "$(CMAKE_BUILD_TYPE)",
        ["CFLAGS:STRING"] = "$(CFLAGS)",
    },
}
```

**Comment by marsam** [comment] 2017-03-01 17:21
I had the time for make a POC.

The package repository must include a `{project-name}-pkg.el` with the a `:build` list containing the build steps.

For example, For the following [`mod-test` module](https://gist.github.com/4359862dc99cf4fc09108174e7772d0d):

```emacs-lisp
(define-package "mod-test" "0.1" "Emacs module example"
  '((emacs "25.1"))
:build ("make"))
```

We need to patch `package.el` to compile use the `:build` instructions:

-   **POC patch for `package.el`:** <https://github.com/marsam/emacs/commit/402c2f3c24>

Should not be significant changes on the package archive, but we need to ensure the **module is packaged as .tar**.

Example melpa recipe for `mod-test`:

```emacs-lisp
(mod-test :repo "https://gist.github.com/4359862dc99cf4fc09108174e7772d0d.git"
          :fetcher git
          :files (:defaults "mod-test.c" "Makefile"))
```

**Comment by vermiculus** [comment] 2017-03-01 18:08
> Giving the user the option to use a pre-compiled module seems like a good compromise.

In this case, we run into the unfortunate dilemma between tracking compiled objects and running untrustworthy code. For the latter, I wonder if we can utilize vagrant or similar virtualization solutions. Set the expectation that a certain `make` target (perhaps the `:build` key's value) will create a binary at a certain location and then just pull the binary out of the vm for packaging.

> we need to ensure the module is packaged as .tar.

What exactly do you mean? I don't see this as a new requirement anywhere in your patch.

**Comment by marsam** [comment] 2017-03-01 23:14
> What exactly do you mean? I don't see this as a new requirement anywhere in your patch.

Sorry, I forgot to mention `package.el`/`package-build.el` only accept two kinds of packages, `single` files and `tar`.

So if we allow to pass a module `mod-test.c` as a `single` file package, we should also need to [patch `package-build.el`](https://github.com/melpa/package-build/blob/9a6824cda477d1bd77d0507b62dcc09ed436b32e/package-build.el#L1240-L1243), and `package.el` with a default target to build the module. So my poc is only applicable with `tar` packages for now.

In the gist, adding both the `mod-test.c` and the `Makefile` to the `:files` key in the recipe makes this a `tar` package.
