### ISSUE TITLE
levenshtein.el file (https://melpa.org/#/levenshtein) is actually a HTML file 

### ISSUE THREAD

**Issue by diegov** [melpa/melpa#4275] opened 2016-09-26 09:25 UTC
Apologies if this isn't the right place to log the issue, I couldn't see a package-specific place to post it.

When requesting the file https://melpa.org/packages/levenshtein-20141029.816.el what is actually returns is a HTML file (maybe the wiki file?)

This is currently breaking cmake-ide.

Cheers,
Diego

**Comment by syohex** [comment] 2016-09-26 16:08
I confirmed. However some other recipes from wiki are not broken.

**Comment by rubicus** [comment] 2016-09-27 09:23
Not only that, but the version number seems to be wrong as well. The file emacs is looking for when I try to install levenshtein is levenshtein-20051013.1056.el, which also happens to be the date the wiki page it's pulling from was edited.

**Comment by purcell** [comment] 2016-09-29 07:24
Thanks. I think that's fixed now. No other wiki recipes were affected.

**Closed by purcell** 2016-09-29 07:24 UTC
