### ISSUE TITLE
Compile error on use-package 20171203.1313

### ISSUE THREAD

**Issue by KrullBorg** [melpa/melpa#5174] opened 2017-12-04 17:32 UTC
Compiling file /home/andreaz/.emacs.d/elpa/use-package-20171203.1313/use-package.el at Mon Dec  4 18:24:23 2017
Entering directory ‘/home/andreaz/.emacs.d/elpa/use-package-20171203.1313/’
use-package.el:43:1:Error: Cannot open load file: File o directory non esistente, up-core

the directory contains only:
use-package.el
use-package-autoloads.el
use-package-pkg.el

**Comment by sparkiegeek** [comment] 2017-12-04 18:51
Dupe of #5171

**Closed** 2017-12-05 07:35 UTC
