### ISSUE TITLE
Can't download melpa archive

### ISSUE THREAD

**Issue by bplx** [melpa/melpa#7238] opened 2020-11-19 18:42 UTC
When i try to run package-refresh-contents it says "Cant download melpa archive" or something like that.
Im on Emacs 27.1, windows 10
debug-on-error output:

```
Debugger entered--Lisp error: (file-error "make client process failed" #("Connection timed out" 0 20 (charset windows-1252)) :name "stable.melpa.org" :buffer #<killed buffer> :host "stable.melpa.org" :service 443 :nowait nil :tls-parameters nil)
  signal(file-error ("make client process failed" #("Connection timed out" 0 20 (charset windows-1252)) :name "stable.melpa.org" :buffer #<killed buffer> :host "stable.melpa.org" :service 443 :nowait nil :tls-parameters nil))
  package--with-response-buffer-1("https://stable.melpa.org/packages/" #f(compiled-function () #<bytecode 0x355239>) :file "archive-contents" :async nil :error-function #f(compiled-function () #<bytecode 0x355245>) :noerror nil)
  package--download-one-archive(("melpa-stable" . "https://stable.melpa.org/packages/") "archive-contents" nil)
  package--download-and-read-archives(nil)
  package-refresh-contents()
  funcall-interactively(package-refresh-contents)
  call-interactively(package-refresh-contents record nil)
  command-execute(package-refresh-contents record)
  execute-extended-command(nil "package-refresh-contents" "package-refresh-contents")
  funcall-interactively(execute-extended-command nil "package-refresh-contents" "package-refresh-contents")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by warsaw** [comment] 2020-11-30 23:04
I've been starting to have a similar problem.  I've been using `https` for both melpa and elpa for a long while but sometime in the not too distant past, `https` is broken.  I get the following error message:

```
error in process sentinel: Error retrieving: https://melpa.org/packages/archive-contents (error connection-failed "connect" :host "melpa.org" :service 443) [2 times]
```

If I switch both the elpa and melpa URLs to use `http`, they work fine.

**Comment by cniles** [comment] 2020-12-01 16:02
Not too long ago support for older versions of TLS were removed.

See:
https://github.com/melpa/melpa/pull/7207
https://github.com/melpa/melpa/issues/7200

Perhaps this is causing the issue?

**Comment by cniles** [comment] 2020-12-01 17:00
Are one or both of you by chance using a proxy?

**Comment by warsaw** [comment] 2020-12-01 19:19
Hi @cniles I am not using a proxy.

I am using Emacs 27.1 on macOS 10.15.7.  All of my installed packages are up to date.  I'll take a look at those referenced issues.

**Comment by warsaw** [comment] 2020-12-01 19:21
Hmm, I don't see any recommendations for things I can change on my side in those referenced issues.  I wonder if this is an Emacs, or elisp problem, a problem with my Emacs configuration, or something weird in my platform.  I don't know enough about how TLS is enabled in Emacs to start to debug this.

**Comment by warsaw** [comment] 2020-12-01 20:03
I've tested this on more than one Mac (one of which is running Big Sur).  None of them work with `https` URLs.

**Comment by cniles** [comment] 2020-12-02 15:31
`(insert (format "%s" (gnutls-available-p)))`

The above command will provide a list of supported cypher capabilities.  E.g, supported features for me on Win 10 w/ 27.1 are:

`(ClientHello Padding Key Share Post Handshake Auth PSK Key Exchange Modes Cookie Supported Versions Early Data Pre Shared Key Session Ticket Record Size Limit Extended Master Secret Encrypt-then-MAC ClientHello Padding Server Certificate Type Client Certificate Type ALPN Heartbeat SRTP Signature Algorithms SRP Supported EC Point Formats Supported Groups OCSP Status Request Maximum Record Size Server Name Indication macs AEAD-ciphers ciphers digests gnutls3 gnutls)`

Some steps to help possibly isolate the problem by eliminating your Emacs configuration:

1.) Start Emacs with command `emacs -Q`
2.) Replace the contents of `*scratch*` with the following:
```
(require 'package)
(add-to-list 'package-archives (cons "melpa" "https://melpa.org/packages/") t)
(package-refresh-contents)
```
3.) `M-x RET eval-buffer RET`
Both elpa and melpa should update.

I'll try to take a deeper look as time allows to help narrow down the cause of the error.

**Comment by warsaw** [comment] 2020-12-03 02:41
The `gnutls-available-p expression gives me:

```
(ClientHello Padding Key Share Post Handshake Auth PSK Key Exchange Modes Cookie Supported Versions Early Data Pre Shared Key Session Ticket Record Size Limit Extended Master Secret Encrypt-then-MAC ClientHello Padding Server Certificate Type Client Certificate Type ALPN SRTP Signature Algorithms SRP Supported EC Point Formats Supported Groups OCSP Status Request Maximum Record Size Server Name Indication macs AEAD-ciphers ciphers digests gnutls3 gnutls)
```

The only difference I can see is that my Emacs doesn't have `Heartbeat`, but other than that I have no idea what this output means, what is expected, or whether the missing `Heartbeat` makes any difference.

Perhaps not though!  I ran the eval-buffer command and it refreshed melpa just fine.  So there must be something in my configs or init files that's causing problems.  I'll do some additional investigation too.

**Comment by warsaw** [comment] 2020-12-03 04:01
Okay, this is truly weird.  I have gotten it to work with the following recipe:

* M-x customize RET group RET package
* Remove melpa.org
* Add the bit of elisp you provide above but *after* I load my `custom.el` file
* Now everything works fine!

So basically, I cannot customize package to add melpa, but after my custom.el is file, I can add it back via explicit elisp, do a package-refresh-contents, and then it works from there.   I'm out of ideas, but I guess I have a workaround?

**Comment by warsaw** [comment] 2020-12-04 01:55
Hmm, I take that back.  Even with my hack, if I come back to the `*Packages*` buffer a day later and hit `g` to refresh, I get the errors again.

**Comment by purcell** [comment] 2020-12-15 01:10
You haven't perhaps overridden the `tls-program` variable, have you, e.g. as mentioned here? https://www.emacswiki.org/emacs/ErcSSL

You could try evaluating

```el
(setq gnutls-log-level 4)
(switch-to-buffer (url-retrieve-synchronously "https://melpa.org/"))
```
and paste the resulting buffer, plus any gnutls debug output in `*Messages*`.

(Separately I'm trying to figure out why our recent SSL configuration changes apparently broke SSL support in Emacs 24.x, at least in some CI environments: in that case, I'm pretty sure that the issue is the inclusion of a much-too-old gnutls library, though that doesn't apply here.)

**Comment by warsaw** [comment] 2020-12-16 04:42
I haven't overridden `tls-program` and I went through my configs and removed all references to ERC (which I used to use but haven't in 3+ years now).  After that, I enabled `https` on both archives and evaled `(setq gnutls-log-level 4)`, then ran `list-packages`.  Attached is the relevant `*Messages*` buffer output.  Nothing stands out to me, but maybe you can make more sense of what's going on!

[log.txt](https://github.com/melpa/melpa/files/5700358/log.txt)

**Comment by omnicr0n** [comment] 2021-01-05 19:10
I wanted to chime in and say I've been having the same problem. The exact message I get is:
`error in process sentinel: Error retrieving: https://melpa.org/packages/archive-contents (error connection-failed "connect" :host "melpa.org" :service 443)`

Oddly enough, whenever I move around the MELPA declaration in `init.el` it works exactly once before not working again (I've tried moving it to the top, middle, and bottom).

I'm running Emacs 27.1 on macOS Catalina 10.15.7

**Comment by purcell** [comment] 2021-01-05 23:39
@warsaw the last few lines of the log indicate that both MELPA *and* GNU ELPA failed:
```
gnutls.c: [2] (Emacs) Deallocating x509 credentials
error in process sentinel: Error retrieving: https://elpa.gnu.org/packages/archive-contents (error connection-failed "connect" :host "elpa.gnu.org" :service 443) [2 times]
gnutls.c: [3] ASSERT: record.c[_gnutls_recv_in_buffers]:1577

gnutls.c: [2] (Emacs) Deallocating x509 credentials
Package refresh done
error in process sentinel: Error retrieving: https://melpa.org/packages/archive-contents (error connection-failed "connect" :host "melpa.org" :service 443) [2 times]
```

@omnicr0n The fact that things work once then stop working suggests a gnutls issue.

I guess what I didn't ask yet is where your Emacs builds came from. I'll grab a 27.1 from emacsformacosx.com and give it a try on my Mac now...

**Comment by purcell** [comment] 2021-01-05 23:44
> I'll grab a 27.1 from emacsformacosx.com and give it a try on my Mac now...

Seems completely fine out-of-the-box fwiw, making multiple successive connections to both package archives.

**Comment by omnicr0n** [comment] 2021-01-05 23:47
@purcell I installed via Homebrew (`brew install --cask emacs`, without anything else).

**Comment by purcell** [comment] 2021-01-06 00:12
> I installed via Homebrew (`brew install --cask emacs`, without anything else).

Which is the same Emacs afaict: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/emacs.rb

**Comment by zentrope** [comment] 2021-01-06 00:32
Compiling Emacs from source/master on MacOS Big Sur (11.2 Beta): I get the same errors reported above when I use HTTPS:

```elisp
(setq package-archives
      (list '("melpa"        . "https://melpa.org/packages/")
            '("gnu"          . "https://elpa.gnu.org/packages/")
            '("org"          . "https://orgmode.org/elpa/")))
```

This is when invoking **package-list-packages**.

If I run **package-refresh-contents** first, _then_ run **package-list-packages**, it works.

However, this configuration:

```elisp
(setq package-archives
      (list '("melpa"        . "http://melpa.org/packages/")
            '("gnu"          . "http://elpa.gnu.org/packages/")
            '("org"          . "https://orgmode.org/elpa/")))
```

works just fine. Note that I have to change _both_ melpa and elpa to HTTPS for things to work as expected, but I do not have to change the org mode URL.

Is there something different about the HTTPS config on orgmode.org vs elpa.gnu.org and melpa.org?

**Comment by warsaw** [comment] 2021-01-06 00:34
I installed railwaycat's Emacs with brew using the [instructions here](https://github.com/railwaycat/homebrew-emacsmacport).

**Comment by omnicr0n** [comment] 2021-01-06 00:35
Yes, I believe so.

I also tried to evaluate the following:
```elisp
(setq gnutls-log-level 4)
(switch-to-buffer (url-retrieve-synchronously "https://melpa.org/"))
```

This is the output from the header: 
```http
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 06 Jan 2021 00:24:09 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 3857
Last-Modified: Tue, 27 Oct 2020 00:41:42 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "5f976cc6-f11"
Strict-Transport-Security: max-age=15768000
Accept-Ranges: bytes
```

After that, I went back to the package list, where it failed to download GNU ELPA as well – similar to @warsaw 
```elisp
gnutls.c: [3] (Emacs) retry: Resource temporarily unavailable, try again.
gnutls.c: [1] (Emacs) non-fatal error: Resource temporarily unavailable, try again.
gnutls.c: [3] ASSERT: record.c[_gnutls_recv_in_buffers]:1577

gnutls.c: [2] (Emacs) Deallocating x509 credentials
error in process sentinel: Error retrieving: https://elpa.gnu.org/packages/archive-contents (error connection-failed "connect" :host "elpa.gnu.org" :service 443) [2 times
```
Though this above error does not occur when I go straight to the package list after firing up Emacs. In that case, it fails on MELPA.

**Comment by warsaw** [comment] 2021-01-06 00:35
And yes, it fails on https for both MELPA and ELPA.

**Comment by purcell** [comment] 2021-01-06 01:11
Launching that same Emacs 27.1 with `-Q` to avoid any interference by my local emacs config, I can repeatedly fetch either archive-contents url with `url-retrieve-synchronously` without seeing such an error. I can't think what else might be interfering.

**Comment by omnicr0n** [comment] 2021-01-06 04:42
@purcell It's odd, as it started randomly one day. I'm new to Emacs and all of the configuration edits I've made are to do with the UI. I tried launching with `-Q` as your post above and it seems to work, so I imagine that means something _is_ wrong with the config itself?

@zentrope
>If I run package-refresh-contents first, then run package-list-packages, it works.

I tried that and it worked for me as well. I tried replacing `https` with `http`, but that doesn't seem to do it for me.
```elisp
error in process sentinel: Error retrieving: http://melpa.org/packages/archive-contents (error connection-failed "connect" :host "melpa.org" :service 443) [2 times]
Package refresh done
```

**Comment by zentrope** [comment] 2021-01-06 05:07
@omnicr0n You might have to restart Emacs after moving from HTTPS to HTTP.

**Comment by xvtstephen** [comment] 2021-01-16 18:07
cannot install any package from melpa on a new emacs install on antiX linux. i can load https sites as prescribed on Getting Started page. then I get:
```
Debugger entered--Lisp error: (file-error "https://melpa.org/packages/ess-20210113.915.tar" "Bad Request")
  signal(file-error ("https://melpa.org/packages/ess-20210113.915.tar" "Bad Request"))
  package-install-from-archive(#s(package-desc :name ess :version (20210113 915) :summary "Emacs Speaks Statistics" :reqs ((emacs (25 1))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "19de88d2b3b2436955ce0f7e6cf8544d4ffaf8ac") (:authors ("David Smith" . "dsmith@stats.adelaide.edu.au") ("A.J. Rossini" . "blindglobe@gmail.com") ("Richard M. Heiberger" . "rmh@temple.edu") ("Kurt Hornik" . "Kurt.Hornik@R-project.org") ("Martin Maechler" . "maechler@stat.math.ethz.ch") ("Rodney A. Sparapani" . "rsparapa@mcw.edu") ("Stephen Eglen" . "stephen@gnu.org") ("Sebastian P. Luque" . "spluque@gmail.com") ("Henning Redestig" . "henning.red@googlemail.com") ("Vitalie Spinu" . "spinuvit@gmail.com") ("Lionel Henry" . "lionel.hry@gmail.com") ("J. Alexander Branham" . "alex.branham@gmail.com")) (:maintainer "ESS Core Team" . "ESS-core@r-project.org") (:url . "https://ess.r-project.org/")) :signed nil))
  mapc(package-install-from-archive (#s(package-desc :name ess :version (20210113 915) :summary "Emacs Speaks Statistics" :reqs ((emacs (25 1))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "19de88d2b3b2436955ce0f7e6cf8544d4ffaf8ac") (:authors ("David Smith" . "dsmith@stats.adelaide.edu.au") ("A.J. Rossini" . "blindglobe@gmail.com") ("Richard M. Heiberger" . "rmh@temple.edu") ("Kurt Hornik" . "Kurt.Hornik@R-project.org") ("Martin Maechler" . "maechler@stat.math.ethz.ch") ("Rodney A. Sparapani" . "rsparapa@mcw.edu") ("Stephen Eglen" . "stephen@gnu.org") ("Sebastian P. Luque" . "spluque@gmail.com") ("Henning Redestig" . "henning.red@googlemail.com") ("Vitalie Spinu" . "spinuvit@gmail.com") ("Lionel Henry" . "lionel.hry@gmail.com") ("J. Alexander Branham" . "alex.branham@gmail.com")) (:maintainer "ESS Core Team" . "ESS-core@r-project.org") (:url . "https://ess.r-project.org/")) :signed nil)))
  package-download-transaction((#s(package-desc :name ess :version (20210113 915) :summary "Emacs Speaks Statistics" :reqs ((emacs (25 1))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "19de88d2b3b2436955ce0f7e6cf8544d4ffaf8ac") (:authors ("David Smith" . "dsmith@stats.adelaide.edu.au") ("A.J. Rossini" . "blindglobe@gmail.com") ("Richard M. Heiberger" . "rmh@temple.edu") ("Kurt Hornik" . "Kurt.Hornik@R-project.org") ("Martin Maechler" . "maechler@stat.math.ethz.ch") ("Rodney A. Sparapani" . "rsparapa@mcw.edu") ("Stephen Eglen" . "stephen@gnu.org") ("Sebastian P. Luque" . "spluque@gmail.com") ("Henning Redestig" . "henning.red@googlemail.com") ("Vitalie Spinu" . "spinuvit@gmail.com") ("Lionel Henry" . "lionel.hry@gmail.com") ("J. Alexander Branham" . "alex.branham@gmail.com")) (:maintainer "ESS Core Team" . "ESS-core@r-project.org") (:url . "https://ess.r-project.org/")) :signed nil)))
  package-install(#s(package-desc :name ess :version (20210113 915) :summary "Emacs Speaks Statistics" :reqs ((emacs (25 1))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "19de88d2b3b2436955ce0f7e6cf8544d4ffaf8ac") (:authors ("David Smith" . "dsmith@stats.adelaide.edu.au") ("A.J. Rossini" . "blindglobe@gmail.com") ("Richard M. Heiberger" . "rmh@temple.edu") ("Kurt Hornik" . "Kurt.Hornik@R-project.org") ("Martin Maechler" . "maechler@stat.math.ethz.ch") ("Rodney A. Sparapani" . "rsparapa@mcw.edu") ("Stephen Eglen" . "stephen@gnu.org") ("Sebastian P. Luque" . "spluque@gmail.com") ("Henning Redestig" . "henning.red@googlemail.com") ("Vitalie Spinu" . "spinuvit@gmail.com") ("Lionel Henry" . "lionel.hry@gmail.com") ("J. Alexander Branham" . "alex.branham@gmail.com")) (:maintainer "ESS Core Team" . "ESS-core@r-project.org") (:url . "https://ess.r-project.org/")) :signed nil) dont-select)
  package-menu--perform-transaction((#s(package-desc :name ess :version (20210113 915) :summary "Emacs Speaks Statistics" :reqs ((emacs (25 1))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "19de88d2b3b2436955ce0f7e6cf8544d4ffaf8ac") (:authors ("David Smith" . "dsmith@stats.adelaide.edu.au") ("A.J. Rossini" . "blindglobe@gmail.com") ("Richard M. Heiberger" . "rmh@temple.edu") ("Kurt Hornik" . "Kurt.Hornik@R-project.org") ("Martin Maechler" . "maechler@stat.math.ethz.ch") ("Rodney A. Sparapani" . "rsparapa@mcw.edu") ("Stephen Eglen" . "stephen@gnu.org") ("Sebastian P. Luque" . "spluque@gmail.com") ("Henning Redestig" . "henning.red@googlemail.com") ("Vitalie Spinu" . "spinuvit@gmail.com") ("Lionel Henry" . "lionel.hry@gmail.com") ("J. Alexander Branham" . "alex.branham@gmail.com")) (:maintainer "ESS Core Team" . "ESS-core@r-project.org") (:url . "https://ess.r-project.org/")) :signed nil)) nil)
  package-menu-execute()
  funcall-interactively(package-menu-execute)
  call-interactively(package-menu-execute nil nil)
  command-execute(package-menu-execute)
  recursive-edit()
  debug()
```
is there a way to install from a local file? but do it properly like it installs from the package manager. I want to avoid manually adding sites and creating modes in my .emacs

**Comment by shaunplee** [comment] 2021-01-16 18:36
There also seems to be some interaction with performing the refresh asynchronously. `(package-refresh-contents nil)` seems to work, while `(package-refresh-contents t)` seems to result in the time out errors discussed above.

`(setq package-menu-async nil)` seems to cause the refresh to occur correctly when doing `M-x list-packages`

**Comment by omnicr0n** [comment] 2021-01-16 19:00
@shaunplee @xvtstephen – I tried both of those things (separately) and both seem to get the job done – thank you!

**Comment by coelhudo** [comment] 2021-04-16 13:26
Setting the gnutls-algorithm-priority variable, as suggested by @xvtstephen, did the trick for me as well

**Comment by warsaw** [comment] 2021-04-16 19:28
> Setting the gnutls-algorithm-priority variable, as suggested by @xvtstephen, did the trick for me as well

I must have missed that recommendation earlier, but it also WFM!  Thank you!

**Comment by caldwell** [comment] 2021-07-30 01:46
I was having this same symptom on a raspberry pi (`Linux raspberrypi 5.10.17+ #1414 Fri Apr 30 13:16:27 BST 2021 armv6l`):
```
error in process sentinel: Error retrieving: https://melpa.org/packages/archive-contents "incomprehensible buffer" [2 times]
error in process sentinel: Error retrieving: https://elpa.gnu.org/packages/archive-contents "incomprehensible buffer" [2 times]
```

The `gnutls-algorithm-priority` tweak also fixed it for me. Thanks!

**Closed** 2021-11-08 23:25 UTC

**Comment by unhammer** [comment] 2023-03-07 10:35
What are the downsides of changing gnutls algorithm priority? (Why is it not set to that by default?)

**Comment by xvtstephen** [comment] 2023-03-10 02:52
there is no downside, this was a bug in emacs. the bug does not exist
in semi-new emacs installs like what you get from debian based distros.
