### ISSUE TITLE
ESS info pages can't be opened

### ISSUE THREAD

**Issue by rm413** [melpa/melpa#7347] opened 2021-01-06 00:18 UTC
ESS info pages can't be opened

# The problem

When trying to see the ESS info pages, I get the following error (see image below).

![image](https://user-images.githubusercontent.com/74389646/103713548-9fcc9c80-4f8a-11eb-891c-fb5f1fbb2e27.png)

# The context

The Emacs shown in the image above was started by executing `emacs -Q` and it is version 27.1.

The following command was executed in order to present a minimal working example.

```
(setq Info-directory-list '("~/.config/emacs/elpa/ess-20210104.1335" "~/.config/emacs/elpa/magit-20201222.1527"))
```

I was able to look at the `Magit` info page. However, I wasn't able to open the `ESS` info page.

# Additional context

Apparently, this issue [had been reported before](https://github.com/melpa/melpa/issues/1097).

**Comment by purcell** [comment] 2021-01-06 00:28
Yeah, there's a bunch of .info files produced, but I guess either upstream doesn't provide an ess.texi or there's a build error. I don't want to get into debugging individual packages if I can help it, but if you clone MELPA and open recipes/ess, then you can hit C-c C-c to build it locally and the output might give some clues.

**Comment by purcell** [comment] 2021-01-06 00:42
The current error looks like the old one, but it's not obvious to me that there has been a regression in the package-build.el code.

**Comment by tarsius** [comment] 2021-01-10 22:11
Generating `ess.info` fails because `ess.texi` contains `@include ../VERSION` and that files does not exist at the time when we run `makeinfo`.

**Comment by purcell** [comment] 2021-01-10 22:27
> Generating `ess.info` fails because `ess.texi` contains `@include ../VERSION` and that files does not exist at the time when we run `makeinfo`.

It does, though. So I think the issue is about relative paths and where makeinfo is run, just like in the prior issue (#1097), but it wasn't obvious to me that anything had changed since @milkypostman's fix.

**Comment by tarsius** [comment] 2021-01-10 22:55
Right, I'll look into it tomorrow.

**Comment by purcell** [comment] 2021-01-12 01:53
The server build logs are now available on the package pages. (In the case of this one, it's extremely long, so I will have to adjust the web site so that a click is necessary to load the logs instead...)

**Comment by tarsius** [comment] 2021-01-12 21:10
I've fixed the regression.

The warnings and errors had nothing to do with that.

The `ess` recipe should be modified, replacing `"doc/*.texi"` with `"doc/ess.texi"`. The other texi files are included in the main file and are not intended to be build by themselves. `"doc/info/dir"` is also unnecessary.

**Comment by purcell** [comment] 2021-01-13 02:55
Done, and yeah, that looks better. I'm going to go ahead and close this: the fixed package should show up in MELPA within a few hours.

**Closed by purcell** 2021-01-13 02:55 UTC
