### ISSUE TITLE
Extraneous and missing packages were created for melpa stable https download page

### ISSUE THREAD

**Issue by andrecbarros** [melpa/melpa#8451] opened 2023-03-20 14:09 UTC
The packages are:
catppuccin-theme-0.2.0.-3.tar
erlang-26.0.-1.1.tar
merlin-4.8.-4.500.tar
merlin-ac-4.8.-4.500.el
merlin-company-4.8.-4.500.el
merlin-iedit-4.8.-4.500.el
mozc-2018.-4.2.-4.26.el

A glitch with the automated scripts, perhaps.

**Comment by milkypostman** [comment] 2023-03-21 05:29
@tarsius Any idea if maybe we messed up versioning recently or there is a glitch in `package.el`?

For example, for `merlin`, the version is `(4 8 -4 500)` but the filename is `merlin-4.8snapshot500` and I'm wondering if that is meaning the listing in broken.

**Comment by tarsius** [comment] 2023-03-21 11:21
It seems there used to be an issue but it is fixed now and a rebuild of these packages has to be forced.

```
 • Building package merlin ...
Package: merlin
Fetcher: github
Source:  https://github.com/ocaml/merlin.git

Updating /home/jonas/src/emacs/elpa/melpa/working/merlin/
Checking out 1fbb47f7559fd4145cee3661cb70e2fae711df53
Copying files (->) and directories (=>)
  from /home/jonas/src/emacs/elpa/melpa/working/merlin/
  to /tmp/merlino9qphc/merlin-4.8snapshot500
  ! emacs/merlin-cap.el -> merlin-cap.el
  ! emacs/merlin-imenu.el -> merlin-imenu.el
  ! emacs/merlin-xref.el -> merlin-xref.el
  ! emacs/merlin.el -> merlin.el
Created merlin-4.8snapshot500.tar containing:
  merlin-4.8snapshot500/
  merlin-4.8snapshot500/merlin-cap.el
  merlin-4.8snapshot500/merlin-imenu.el
  merlin-4.8snapshot500/merlin-pkg.el
  merlin-4.8snapshot500/merlin-xref.el
  merlin-4.8snapshot500/merlin.el
Built merlin in 5.590s, finished at 2023-03-21T10:35:47+0000
 ✓ Success:
4.0K -rw-r--r-- 1 jonas users  369 Mar 21 11:35 packages-stable/merlin-4.8snapshot500.entry
100K -rw-r--r-- 1 jonas users 100K Mar 21 11:35 packages-stable/merlin-4.8snapshot500.tar
```

----

Another problem is that `4.8-500` is intended to be larger than `4.8`. Unfortunately `version<` and friends only support pre-releases but not patches, as used, e.g., by this package or Debian (see https://manpages.debian.org/wheezy/dpkg-dev/deb-version.5.en.html).

I had a few conversations with Stefan Monnier about this. The result was that I adjusted my version strings I use in my packages to indicate "this isn't a release, it is an arbitrary commit following release N". I switched that from `N-git` (which actually is considered smaller than N) to `N.50-git`.

I think it would be a good idea if `version<` learned about "patch releases". My `vcomp` package supports that and isn't much more complicated (but requires an uglier internal format). `N-M` and `N-pM` should be larger than `N`, but other known suffix strings should be treated as smaller, e.g., `N-alphaM` < `N`.

But I don't feel like having that conversation on `emacs-devel`, as that suggestion would undoubtedly be controversial and would have to be discussed at length. But if someone else would take on the task to convince others of the need for this, that would be great. Of course that would mean that `version<` would have to be distributed as part of a "core" package, a package that is part of Emacs but is also distributed on GNU Elpa, otherwise we wouldn't be able to benefit for another half-dozen years. (`package` should also be distributed on GNU Elpa, maybe the version functions could be made part of the `package` package.)

----

Meanwhile we have to somehow deal with tags that contain more than numbers and dots. These come in two variants:

1. `catppuccin-theme` currently has two tags `V0.1.0` and `V0.2.0-alpha`. `version<` handles these as intended, but since Melpa Stable is supposed to distribute releases, not pre-releases, we should actually ignore `V0.2.0-alpha`.
2. Packages that use incompatible post/patch-release tags. Since `version<` cannot handle those, we should ignore those as well, and inform the maintainers about the issue, so that they can start using compatible tags.

To complicate things further, all the packages in the second group are maintain in large repositories that contain much more than just the Elisp package. The maintainers of those repositories won't switch the style of their tags just for the Elisp part.

Maintaining Elisp as a tiny part of a large repository is problematic. This issue is just another problem that can arise when doing so. #5361 and #8172 are about getting the upstreams to split out the Elisp into separate repositories. I have also opened issues about this in some of the upstream repositories, with some, but not nearly complete` success. This doesn't include any of the packages affected by this particular issue. Maybe someone else would like to take on the task of convincing the maintainers to split out the Elisp?

----

So IMO, in the short to midterm, `package-build` should simply ignore tags that contain more than numbers and dots.

**Comment by andrecbarros** [comment] 2023-03-21 15:52
On those cases where the maintainers use alpha, beta, gamma, snapshot, pre and so on, why not add a '+' followed by the original string?

On cases exposed above, we would get:
V0.2.0-alpha -> 0.2.0+alpha, which seems to be valid for .deb and .rpm

On a slightly more detailed case:
merlin-4.8snapshot500 -> merlin-4.8+snapshot500

This way the comparison can be honored as '+' is, actually, less than '-', '[:alnum:]' and '.' on ascii table.

**Comment by tarsius** [comment] 2023-03-21 16:47
> why not add a '+' followed by the original string?

Because `version<` and by extension `package.el` does not support that.

**Comment by andrecbarros** [comment] 2023-03-22 10:52
I don't now what versions< does, but, comparing cases:

**Comment by andrecbarros** [comment] 2023-03-22 20:04
Whoa, sorry, I didn't want to cause any trouble, I was just reporting an issue in one project I'm glad exist and that have been useful for me through years.

**Comment by tarsius** [comment] 2023-03-22 20:27
Np. I just had to make it clear that I don't want to have a conversation about this at this time.

Reopening because the maintainers should still discuss the issues I mentioned.

**Comment by tarsius** [comment] 2023-06-09 16:35
> So IMO, in the short to midterm, `package-build` should simply ignore tags that contain more than numbers and dots.

We are doing that now. If that causes problems for individual packages, we can set `:version-regexp` in their recipes.

**Closed by tarsius** 2023-06-09 16:35 UTC
